### Alle ToDos Abfragen
GET http://localhost:8080/todo HTTP/1.1

### Eine ToDo eintragen
POST http://localhost:8080/todo HTTP/1.1
content-type: Application/JSON

{
    "title":"ich bin neuer hier",
    "date": "2020-01-01",
    "proId": 17,
    "priId": 17
}

### Eine ToDo löschen
DELETE http://localhost:8080/todo/3 HTTP/1.1

### Eine ToDo aktualisieren
PUT http://localhost:8080/todo/50 HTTP/1.1
content-type: Application/JSON

{
    "title":"etwas machen neuer",
    "proId":13,
    "date": "2022-01-01"
}




### Alle Projekte Abfragen
GET http://localhost:8080/project/13 HTTP/1.1

### Eine Projekt anlegen
POST http://localhost:8080/project HTTP/1.1
content-type: Application/JSON

{
    "name":"neues Projekt3"
}

### Eine Projekt löschen
DELETE http://localhost:8080/project/2 HTTP/1.1

### Eine Projekt aktualisieren
PUT http://localhost:8080/project/18 HTTP/1.1
content-type: Application/JSON

{
    "name":"neuer Name3"
}



### Alle Prioritäten Abfragen
GET http://localhost:8080/priority HTTP/1.1

### Eine Priorität anlegen
POST http://localhost:8080/priority HTTP/1.1
content-type: Application/JSON

{
    "value":2,
    "description":"sehr wichtig"
}

### Eine Priorität löschen
DELETE http://localhost:8080/priority/13 HTTP/1.1

### Eine Priorität aktualisieren
PUT http://localhost:8080/priority/19 HTTP/1.1
content-type: Application/JSON

{
    "value":10,
    "description":"unwichtig"
}


### Powershell
Invoke-RestMethod -Method Delete -Uri "http://localhost:8080/priority/3"