name: CI/CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build with Maven
    runs-on: ubuntu-latest
    container:
      image: maven:latest
    env:
      MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Maven dependencies
        run: mvn dependency:go-offline

      - name: Build Project
        run: mvn package

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: todo-jar
          path: target/todo-todo-jar-with-dependencies.jar

  docker_build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: deploy
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: todo-jar
          path: target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log Docker Info
        run: docker info

      - name: Build Docker Image
        run: docker build .
